- name: Full provision app server
  hosts: app
  become: true

  roles:
    - docker
    - app
    - app_prod
    - app_dev
    - caddy
    - node_exporter

- name: Full provision monitoring server
  hosts: monitoring
  become: true

  roles:
    - monitoring
    - node_exporter
    - prometheus
    - blackbox_exporter