- name: Pull PROD image from registry
  community.docker.docker_image:
    name: "{{ app_image_name }}:prod"
    source: pull
    force_source: true

- name: Stop old devops-app-prod container if exists
  community.docker.docker_container:
    name: devops-app-prod
    state: absent

- name: Run devops-app-prod container
  community.docker.docker_container:
    name: devops-app-prod
    image: "{{ app_image_name }}:prod"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "127.0.0.1:5000:5000"
    env:
      APP_NAME: "devops-app-prod"
      APP_ENV: "prod"
      APP_VERSION: "{{ app_version }}"
