- name: Stop old nginx test container if exists
  community.docker.docker_container:
    name: nginx-test
    state: absent

- name: Stop old devops-app-2 container if exists
  community.docker.docker_container:
    name: devops-app-2
    state: absent
