name: Ansible Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 178.104.14.77 >> ~/.ssh/known_hosts
          ssh-keyscan -H 195.201.19.195 >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ansible-playbook playbook.yml
